# Generated by Django 6.0 on 2026-08-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martapp', '0004_category_image_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
