# Generated by Django 6.0 on 2026-08-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martapp', '0005_herobanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herobanner',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='herobanner',
            name='button_link',
            field=models.CharField(default='#products', max_length=200),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='button_text',
            field=models.CharField(default='Browse Products', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(upload_to='hero_banners/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
